// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using TravelPlanner.API.Data;

#nullable disable

namespace TravelPlanner.API.Migrations
{
    [DbContext(typeof(TravelPlannerDbContext))]
    [Migration("20260423182209_UpdatePhoneNullable")]
    partial class UpdatePhoneNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.API.Models.AuthChallenge", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("ChallengeToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("challenge_token");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("used_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("auth_challenges", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Business", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<ulong>("CategoryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<Point>("GeoPoint")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasColumnName("geo_point");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("opening_hours");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_businesses_category");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("idx_businesses_latlng");

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Category", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('location','business','both')")
                        .HasDefaultValue("both")
                        .HasColumnName("category_type");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Itinerary", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EndLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("end_location");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("StartLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("start_location");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('draft','generated','completed','cancelled')")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TripDate")
                        .HasColumnType("DATE")
                        .HasColumnName("trip_date");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_itineraries_user");

                    b.ToTable("itineraries", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.ItineraryItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("BusinessId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("ItineraryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("itinerary_id");

                    b.Property<ulong?>("LocationId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PlannedEndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("planned_end_time");

                    b.Property<DateTime?>("PlannedStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("planned_start_time");

                    b.Property<uint>("SortOrder")
                        .HasColumnType("int unsigned")
                        .HasColumnName("sort_order");

                    b.Property<decimal?>("TravelDistanceKm")
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("travel_distance_km");

                    b.Property<uint?>("TravelMinutes")
                        .HasColumnType("int unsigned")
                        .HasColumnName("travel_minutes");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("idx_itinerary_business");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("idx_itinerary_location");

                    b.HasIndex("ItineraryId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_itinerary_order");

                    b.ToTable("itinerary_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_itinerary_target", "(location_id IS NOT NULL AND business_id IS NULL) OR (location_id IS NULL AND business_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Location", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("district");

                    b.Property<int>("EstimatedCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("estimated_cost");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_id");

                    b.Property<Point>("GeoPoint")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasColumnName("geo_point");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("province");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("DECIMAL(3,2)")
                        .HasColumnName("rating");

                    b.Property<string>("RawJson")
                        .HasColumnType("JSON")
                        .HasColumnName("raw_json");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("geoapify")
                        .HasColumnName("source");

                    b.Property<string>("Subcategory")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("subcategory");

                    b.Property<string>("SuggestedDuration")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("suggested_duration");

                    b.Property<string>("Tags")
                        .HasColumnType("JSON")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_locations_category");

                    b.HasIndex("City")
                        .HasDatabaseName("idx_locations_city");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_locations_external_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_locations_name");

                    b.HasIndex("Region")
                        .HasDatabaseName("idx_locations_region");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.LocationSeedJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FetchedTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("fetched_total");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("finished_at");

                    b.Property<int>("InsertedTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("inserted_total");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("geoapify_places")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<int>("LastOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("last_offset");

                    b.Property<int>("LastPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1)
                        .HasColumnName("last_page");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("region_name");

                    b.Property<int>("SkippedTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("skipped_total");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','running','done','failed')")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RegionName", "JobType")
                        .IsUnique()
                        .HasDatabaseName("uq_seed_region_jobtype");

                    b.ToTable("location_seed_jobs", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.RefreshToken", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Review", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("BusinessId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("business_id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<ulong?>("LocationId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("location_id");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("rating");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("LocationId");

                    b.HasIndex("Rating")
                        .HasDatabaseName("idx_reviews_rating");

                    b.HasIndex("UserId", "BusinessId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_business_review");

                    b.HasIndex("UserId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_location_review");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("chk_review_rating", "rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("chk_review_target", "(location_id IS NOT NULL AND business_id IS NULL) OR (location_id IS NULL AND business_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TravelPlanner.API.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('user','admin')")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.UserPreference", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<ulong>("CategoryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.API.Models.VisitHistory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("BusinessId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("DistanceMeters")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("distance_meters");

                    b.Property<Point>("GpsPoint")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasColumnName("gps_point");

                    b.Property<ulong?>("LocationId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("location_id");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<decimal>("UserLatitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("user_latitude");

                    b.Property<decimal>("UserLongitude")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("user_longitude");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_visit_user");

                    b.ToTable("visit_history", null, t =>
                        {
                            t.HasCheckConstraint("chk_visit_target", "(location_id IS NOT NULL AND business_id IS NULL) OR (location_id IS NULL AND business_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TravelPlanner.API.Models.AuthChallenge", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.User", "User")
                        .WithMany("AuthChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Business", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.Category", "Category")
                        .WithMany("Businesses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Itinerary", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.User", "User")
                        .WithMany("Itineraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.ItineraryItem", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.Business", "Business")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelPlanner.API.Models.Itinerary", "Itinerary")
                        .WithMany("Items")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelPlanner.API.Models.Location", "Location")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Business");

                    b.Navigation("Itinerary");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.RefreshToken", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Review", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.Business", "Business")
                        .WithMany("Reviews")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelPlanner.API.Models.Location", "Location")
                        .WithMany("Reviews")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelPlanner.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.UserPreference", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.Category", "Category")
                        .WithMany("UserPreferences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelPlanner.API.Models.User", "User")
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.VisitHistory", b =>
                {
                    b.HasOne("TravelPlanner.API.Models.Business", "Business")
                        .WithMany("VisitHistories")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelPlanner.API.Models.Location", "Location")
                        .WithMany("VisitHistories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelPlanner.API.Models.User", "User")
                        .WithMany("VisitHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Business", b =>
                {
                    b.Navigation("ItineraryItems");

                    b.Navigation("Reviews");

                    b.Navigation("VisitHistories");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Category", b =>
                {
                    b.Navigation("Businesses");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Itinerary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.Location", b =>
                {
                    b.Navigation("ItineraryItems");

                    b.Navigation("Reviews");

                    b.Navigation("VisitHistories");
                });

            modelBuilder.Entity("TravelPlanner.API.Models.User", b =>
                {
                    b.Navigation("AuthChallenges");

                    b.Navigation("Itineraries");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("UserPreferences");

                    b.Navigation("VisitHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
